config/routes.rb
Rails.application.routes.draw do
  
  root to: "welcome#index"

  get "/trips/:trip_id/check_points/new" => "check_points#new"

  get '/users/current', to: 'users#current'
  
  get '/login', to: 'sessions#new'

  get '/logout', to: 'sessions#destroy'

  get '/auth/facebook/callback', to: 'sessions#create'

  # resources :trips #do 
  resources :check_points
  resources :trips
  #end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/check_point.rb
class CheckPoint < ActiveRecord::Base
  belongs_to :trip
  has_many :reviews
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :check_points
  validates_presence_of :user_id, :origin, :destination, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :trips
  has_many :check_points, through: :trips  
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/check_points_controller.rb
class CheckPointsController < ApplicationController

  def new
    @checkpoint = CheckPoint.new(checkpoint_params_for_new)
    @yelp_url = ""
    @businesses = []
    if @checkpoint.latitude || @checkpoint.longitude
      @yelpdata = Yelp.client.search_by_coordinates({latitude: "#{@checkpoint.latitude}", longitude: "#{@checkpoint.longitude}"}, {limit: 20, sort: 1, radius_filter: 40000 })
      @yelpdata.raw_data["businesses"].each do |business|
        if (@checkpoint.name.include?(business["name"][0..5]) || business["name"].include?(@checkpoint.name[0..5]))
          @yelp_url = business['url']
          @image = business["image_url"]
          @rating = business["rating"]
          @number = business["display_phone"].gsub("+","")
          @review_count = business["review_count"]
          @stars = business["rating_img_url_large"]
        end
      end
    end
    @yelp_url
  end

  def show
    @checkpoint = CheckPoint.find(params[:id])
     @yelpdata = Yelp.client.search_by_coordinates({latitude: "#{@checkpoint.latitude}", longitude: "#{@checkpoint.longitude}"}, { term: "food, restaurants",limit: 20, sort: 1, radius_filter: 40000 })
    @yelp_url = ""
    @yelpdata.raw_data["businesses"].each do |business|
      if (@checkpoint.name.include?(business["name"][0..5]) || business["name"].include?(@checkpoint.name[0..5]))
        @yelp_url = business['url']
        @image = business["image_url"]
        @rating = business["rating"]
        @number = business["phone"]
        @review_count = business["review_count"]
        @stars = business["rating_img_url_large"]
      end
    end
    @yelp_url
  end

  def create
    @checkpoint = CheckPoint.new(checkpoint_params)
    respond_to do |format|
      if @checkpoint.save
        format.html { redirect_to @checkpoint.trip, notice: 'checkpoint was successfully created.' }
        format.json { render :show, status: :created, location: @checkpoint }
      else
        format.html { render :new }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @checkpoint = CheckPoint.find(params[:id])
    @checkpoint.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'checkpoint item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  def checkpoint_params_for_new
    params.permit(:name, :address, :trip_id, :latitude, :longitude)
  end

  def checkpoint_params
    params.require(:check_point).permit(:name, :address, :trip_id, :latitude, :longitude)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new
   redirect_to '/auth/facebook'
 end

 def create
   user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
   log_in(user)
   redirect_to root_path
 end

 def auth
   request.env['omniauth.auth']
 end

 def destroy
   log_out
   redirect_to root_path
 end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def show
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.new(trip_params)
    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :origin, :destination, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def current
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @trip = Trip.new
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_points_helper.rb
module CheckPointsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

 def log_in(user)
   session[:user_id] = user.id
 end

 def log_out
   session.delete(:user_id)
   @current_user = nil
 end

 def current_user
   @current_user ||= User.find_by(id: session[:user_id])
 end

 def logged_in?
   !current_user.nil?
 end

 def login_logout_links
   if logged_in?
     link_to 'Logout', logout_path
   else
     link_to 'Log in with Facebook!', login_path
   end
 end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/check_points/_form.html.erb
<%= form_for(@checkpoint) do |f| %>
 <% if @checkpoint.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@checkpoint.errors.count, "error") %> prohibited this checkpoint from being saved:</h2>

     <ul>
     <% @checkpoint.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
  <%= f.hidden_field :name, :value => @checkpoint.name %>
  <%= f.hidden_field :address, :value => @checkpoint.address %>
  <%= f.hidden_field :latitude, :value => @checkpoint.latitude %>
  <%= f.hidden_field :longitude, :value => @checkpoint.longitude %>
 </div>
 <%= f.hidden_field :trip_id, :value => @checkpoint.trip_id %>
 <div class="actions">
   <%= f.submit "Add to Trip?", class: "btn btn-default" %>
 </div>
<% end %>

app/views/check_points/new.html.erb
<br>
<div class="row">
  <div class="col-md-6">
    <iframe
      width= "70%"
      height="450"
      frameborder="0" style="border:0"
      src='https://www.google.com/maps/embed/v1/place?key=<%="#{ENV["GOOGLE_KEY"]}"%>&q=<%=@checkpoint.name+@checkpoint.address%>'>
    </iframe>
  </div>
  <div class="col-md-6">
    <h2><%= @checkpoint.name %></h2><br>
    <h3><%= @checkpoint.address %></h3>
    <% if @yelp_url != "" %>
      <%= image_tag @image %><br>
      <h4>Phone number: <%= @number %></h4>
      <h4>No. of Reviews: <%= @review_count %></h4>
      <h4>Average Rating: <%= @rating %></h4>
      <%= image_tag @stars %>
    <% end %>

    <% if @yelp_url == "" %>
      <h4>A yelp review is not available for this restaurant</h4>
    <% else %>
      <h4><%= link_to "Visit their Yelp page!", @yelp_url, class: "yelp-link" %></h4>
    <% end %>
    <br>
    <%= render 'form' %>
  </div>
</div>

app/views/check_points/show.html.erb
<br>
<div class="row">
  <div class="col-md-6">
    <br><br>
    <iframe
      width= "70%"
      height="450"
      frameborder="0" style="border:0"
      src='https://www.google.com/maps/embed/v1/place?key=<%="#{ENV["GOOGLE_KEY"]}"%>&q=<%=@checkpoint.name+@checkpoint.address%>'>
    </iframe>
  </div>
  <div class="col-md-6">
    <h2><%= @checkpoint.name %></h2>
    <h3><%= @checkpoint.address %></h3>
    <% if @yelp_url != "" %>
      <%= image_tag @image %><br>
      Phone number: <%= @number %><br>
      No. of Reviews: <%= @review_count %><br>
      Average Rating: <%= @rating %><br>
      <%= image_tag @stars %>
    <% end %>

    <% if @yelp_url == "" %>
      <h4>A yelp review is not available for this restaurant</h4>
    <% else %>
      <h4><%= link_to "Visit their Yelp page!", @yelp_url %></h4>
    <% end %>
    <h3>This restaurant has been added to your trip!</h3>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="header-full-top" class="hidden-xs header-full">
  <div class="navbar navbar-default " role="navigation">
   <div class="container-fluid">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="/">Along The Way</a>
     </div>
     <div class="collapse navbar-collapse">
       <ul class="nav navbar-nav">
            <li><%= link_to current_user.name, users_current_path %></li>
       </ul>
       <ul class="nav navbar-nav navbar-right">
            <li id="back"><%= link_to 'Back', :back %></li>
            <li><%= login_logout_links %></li>
          </ul>
     </div><!-- navbar -->

    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Along The Way</title>
   <%= stylesheet_link_tag 'application', ''%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <script type="text/javascript"> var idx=window.location.toString().indexOf("#_=_"); if (idx>0) { window.location = window.location.toString().substring(0, idx); } </script>
</head>
  <body>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
    <%= render '/layouts/header' %>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>

<%= javascript_tag do %>
  var tripId = <%= @trip.id %>
  var start = <%= @trip.origin.to_json.html_safe %>;
  var end = <%= @trip.destination.to_json.html_safe %>;
  var waypoints = <%= @trip.check_points.to_json.html_safe %>
<% end %>
<!-- 
<script type="text/javascript"
  src='https://maps.googleapis.com/maps/api/js?key=<%#="#{ENV['GOOGLE_KEY']}"%>'>
</script> -->

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>

<div class="row">
  <div id="directions-panel"></div>
  

  <div id="map-canvas"></div>
  <div id="panel">
    <input type=button value="Delete Pins">
  </div>
</div>
<% if @trip.check_points.count > 0 %>
  <div class="checkpoints">
    <h4 style= "color: black;">Places I've been for this trip</h4>
      <ol type= "A">
        <li style= "visibility: hidden;"></li>
      <% @trip.check_points.each do |checkpoint| %>
        <li><%= link_to "#{checkpoint.name}- #{checkpoint.address}", check_point_path(checkpoint) %> <%= button_to "Remove from trip", check_point_path(checkpoint), :method => :delete, class: "btn btn-default" %> </li>
      <% end %>
      </ol>
  </div>
<% end %>

app/views/users/current.html.erb
<h1>Where I've been</h1>
  <% @user.trips.each do |trip| %>

<div class="panel panel-warning">
  <div class="panel-heading">
    <h2 class="panel-title" id="panel-title"><%=link_to trip.name, trip_path(trip)%></h3>
  </div>
  <div class="panel-body">
    <h4 style="color: black;">Origin: <%= trip.origin %></h4>
    <% if trip.check_points.count > 0 %>
      <h4 style="color: black;">Along the way:</h4>
      <ul>
      <% trip.check_points.each do |checkpoint| %>
        <li><%= link_to checkpoint.name, check_point_path(checkpoint) %>
        <%= checkpoint.address %></li>
      <% end %>
      </ul>
    <% end %>
    <h4 style="color: black;">Destination:<%= trip.destination %></h4>
    <h4 style="color: black;">Started trip on: <%= trip.created_at.strftime("%B %d, %Y") %></h4>
  </div>

</div>
  <% end %>

app/views/welcome/_form.html.erb
<%= form_for @trip, html: { class: "form-inline" } do |f| %>
 <% if @trip.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

     <ul>
     <% @trip.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="form-group">
   <%= f.label :name, "Name Of Trip" %><br>
   <%= f.text_field :name, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :origin %><br>
   <%= f.text_field :origin, id: "start",class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :destination %><br>
   <%= f.text_field :destination, id: "end",class: "form-control" %>
 </div>
 <br>
 <br>
 <div class="actions">
 <%= f.hidden_field :user_id, :value => current_user.id %>
   <%= f.submit "Let's Go!", class: "btn btn-default"%>
 </div>
<% end %>

app/views/welcome/index.html.erb
<center><h1 id="roadtrip">Along The Way</h1></center><br><br><br>

  <% if logged_in? %>
  	<center><%= render 'form'  %></center>
  <% else %>
  	<h3>Please log in to continue</h3>
  <% end %>